/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'varun' at '7/12/15 7:45 AM' with Gradle 2.4
 *
 * @author varun, @date 7/12/15 7:45 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
